name: Build and Deploy 

on:
  push:
    branches:
      - main

jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install
        run: |
          npm ci
          npm run build --if-present
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build


